replace canvasGraph with canvasSvg in non-existence check in equal to saved import test
Cypress version 12.0.0 seems to have made finding from a non-existent
element timeout.

This avoids this error message:

  1) Browser save and open
       A DOT source that is imported from the dot parameter in the URL and is equal to a saved graph in browser local storage does not create a new graph even if that graph is not the current g
raph:
     CypressError: Timed out retrying after 10000ms: `cy.find()` failed because it requires a DOM element or document.

No elements in the current DOM matched your query:

  > cy.get(#canvas).find(svg)
      at isElement (http://localhost:3000/__cypress/runner/cypress_runner.js:144409:62)
      at validateType (http://localhost:3000/__cypress/runner/cypress_runner.js:144267:14)
      at Object.isType (http://localhost:3000/__cypress/runner/cypress_runner.js:144298:7)
      at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:134720:24)
      at Object.subjectFn (http://localhost:3000/__cypress/runner/cypress_runner.js:143314:16)
      at $Cy.verifyUpcomingAssertions (http://localhost:3000/__cypress/runner/cypress_runner.js:142658:31)
      at onRetry (http://localhost:3000/__cypress/runner/cypress_runner.js:143305:15)
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:1807:23)
      at Promise.attempt.Promise.try (http://localhost:3000/__cypress/runner/cypress_runner.js:4315:29)
      at whenStable (http://localhost:3000/__cypress/runner/cypress_runner.js:143192:68)
      at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:143133:14)
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:1807:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:1519:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:1576:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:1621:10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:1701:18)
      at Promise._fulfill (http://localhost:3000/__cypress/runner/cypress_runner.js:1645:18)
      at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:5450:46)
  From Your Spec Code:
      at Context.eval (webpack://graphviz-visual-editor/./cypress/e2e/browser_save_and_open.spec.js:1119:21)