port cypress.config.js to ESM and temorarily rename with .mjs extension
The .mjs extension is necessary to make Node.js interpret this file as
an ES module. This is a temporary measure until an upcoming commit
sets "type": "module" in the package.json. Without this, we get this
error message:

Your configFile is invalid: /home/magjac/graphviz-visual-editor/cypress.config.js

It threw an error when required, check the stack trace below:

/home/magjac/graphviz-visual-editor/cypress.config.js:1
import { defineConfig } from 'cypress';
^^^^^^

SyntaxError: Cannot use import statement outside a module