replace canvasGraph with canvasSvg in non-existence check in not equal import test
Cypress version 12.0.0 seems to have made finding from a non-existent
element timeout.

This avoids this error message:

  1) Browser save and open
       A DOT source that is imported from the dot parameter in the URL creates a new graph in browser local storage if not equal to any existing DOT source:
     CypressError: Timed out retrying after 10000ms: `cy.find()` failed because it requires a DOM element or document.

No elements in the current DOM matched your query:

  > cy.get(#canvas).find(svg)
      at isElement (http://localhost:3000/__cypress/runner/cypress_runner.js:157073:70)
      at validateType (http://localhost:3000/__cypress/runner/cypress_runner.js:156912:14)
      at Object.isType (http://localhost:3000/__cypress/runner/cypress_runner.js:156947:7)
      at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:145776:24)
      at Object.subjectFn (http://localhost:3000/__cypress/runner/cypress_runner.js:154817:16)
      at $Cy.verifyUpcomingAssertions (http://localhost:3000/__cypress/runner/cypress_runner.js:134218:31)
      at onRetry (http://localhost:3000/__cypress/runner/cypress_runner.js:154809:15)
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:11327:23)
      at Promise.attempt.Promise.try (http://localhost:3000/__cypress/runner/cypress_runner.js:8601:29)
      at whenStable (http://localhost:3000/__cypress/runner/cypress_runner.js:151463:65)
      at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:150871:14)
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:11327:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:9262:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:9319:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:9364:10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:9444:18)
      at Promise._fulfill (http://localhost:3000/__cypress/runner/cypress_runner.js:9388:18)
      at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:11002:46)
  From Your Spec Code:
      at Context.eval (webpack:///./cypress/e2e/browser_save_and_open.spec.js:971:21)